schema_version: 1

context:
  name: stanhf
  version: "1.1.0"
  python_min: "3.8"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/stanhf-${{ version }}.tar.gz
  sha256: 1158976afdea6dbb25ff441d0ed8531fa29b8e1dda8d29f507f7fbdc9768771d

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - stanhf = stanhf.cli:cli

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - pip
  run:
    - python >=${{ python_min }}
    - arviz
    - matplotlib-base
    - click
    - click-help-colors
    - cmdstanpy
    - numpy
    - pyhf

tests:
  - python:
      imports:
        - stanhf
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - stanhf --help

about:
  license: GPL-3.0-only
  license_file: LICENSE
  summary: stanhf
  homepage: https://github.com/xhep-lab/stanhf
  repository: https://github.com/xhep-lab/stanhf

extra:
  recipe-maintainers:
    - andrewfowlie
